let cAboutBR1 = "";
cAboutBR1 += "Geminiana, resiliente, analista de sistemas. Ha 10 anos e um pouco mais tenho trabalhado como analista de negocios e devenvolvimento (linguagem advpl). ";  
cAboutBR1 += "Disciplinada, coerente, apta em solucionar conflitos e com grande capacidade de me adaptar. ";
let cAboutBR2 = "";
cAboutBR2 += "Mas a estabilidade nao me impede de procurar por experiências desafiadoras em minha carreira. ";  
cAboutBR2 += "Um exemplo, estou aprimorando meus conhecimentos de programacao web e estudando para o IELTS";
let cAboutBR3 = "";
cAboutBR3 += "Afinal, um profissional deve continuar em letante evolução. "; 

let cAboutEN1 = "";
cAboutEN1 += "Geminian, resilient, systems analyst. For 10 years and a little longer I have been ";  
cAboutEN1 += "working as a business and development analyst (advpl language). Disciplined, coherent, "; 
cAboutEN1 += "able to resolve conflicts and with great ability to adapt.";
let cAboutEN2 = "";
cAboutEN2 += "But stability doesn't stop me from looking for challenging experiences in my career. For instance, "; 
cAboutEN2 += "I am improving my knowledge of web development and also studying for IELTS.";
let cAboutEN3 = "";
cAboutEN3 += "After all, a professional must continue in letant evolution. ";

let edcBR = "Educacao";
let edc1BR = "Lato Sensu em Engenharia de Sistemas"; 
let edc2BR = "ESAB - Escola Superior Aberta do Brasil"; 
let edc3BR = "Bacharelado em Sistemas de Informação"; 
let edc4BR = "FAZU - Faculdades Associadas de Uberaba";
let edc5BR = "Técnico em Informática"; 
let edc6BR = "IFTM - Instituto Federal do Triângulo Mineiro"; 
let edc7BR = "Ingles: fluente. projeto IELTS 2022"; 
let edc8BR = "Frances: iniciante"; 

let expBR = "Experiencia";
let exp1BR = "Cargo -> Analista de Sistemas / analista de negócios ";
let exp2BR = "Atendimento ao cliente interno sistema de gestão Protheus PLS/banco de dados Oracle";
let exp3BR = "Análise de requisitos para desenvolvimento e implantação de relatórios e telas.";
let exp4BR = "Cargo -> Desenvolvedor Junior";
let exp5BR = "Atendimento ao cliente interno sistema de gestão desenvolvido pela empresa";
let exp6BR = "Análise de requisitos para desenvolvimento e implantação de relatórios e telas.";
let exp7BR = "Cargo -> Estagiária em manutenção de hardware/software";
let exp8BR = "Atendimento ao cliente interno buscando solucionar possíveis problemas referentes ";
let exp9BR = "a equipamentos e instalações de softwares";
let exp10BR = "Donwload curriculo completo"

let edcEN = "Education";
let edc1EN = "Lato Sensu in Systems Engineering";
let edc2EN = "ESAB - Escola Superior Aberta do ENasil";
let edc3EN = "Bachelor of Information Systems";
let edc4EN = "FAZU - Faculdades Associadas de Uberaba";
let edc5EN = "Computer Technician";
let edc6EN = "IFTM - Federal Institute of Triangulo Mineiro";
let edc7EN = "English: fluent. IELTS 2022 project";
let edc8EN = "French: beginner";

let expEN = "Experience";
let exp1EN = "Position -> Systems Analyst / Business Analyst ";
let exp2EN = "Internal customer service Protheus PLS management system/Oracle database";
let exp3EN = "Requirements analysis for developing and deploying reports and screens.";
let exp4EN = "Position -> Junior Developer";
let exp5EN = "Internal customer service management system developed by the company";
let exp6EN = "Requirements analysis for developing and deploying reports and screens.";
let exp7EN = "Position -> Intern in hardware/software maintenance";
let exp8EN = "Internal customer service seeking to solve possible issues regarding equipment and ";
let exp9EN = "software installations";
let exp10EN = "Download complete resume"